downstream_package_name: python-requests-file
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-29-x86_64
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
  trigger: pull_request
specfile_path: python-requests-file.spec
synced_files:
- python-requests-file.spec
- .packit.yaml
upstream_package_name: requests-file
